//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegCheckService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://regcheck.org.uk", ConfigurationName="RegCheckService.CarRegSoap")]
    public interface CarRegSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CarSpecifications", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.DataGrid> CarSpecificationsAsync(string make, string model, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/WheelSize", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> WheelSizeAsync(string make, string model, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/UKMOT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.UKMOTData> UKMOTAsync(string RegistrationNumber, string Model, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckSouthAfrica", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckSouthAfricaAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckEstonia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckEstoniaAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckNewZealand", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckNewZealandAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckUSA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckUSAAsync(string RegistrationNumber, string State, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckAustralia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckAustraliaAsync(string RegistrationNumber, string State, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckSpain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckSpainAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckFrance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckFranceAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckDenmark", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckDenmarkAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckFinland", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckFinlandAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckSweden", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckSwedenAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckNorway", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckNorwayAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckPortugal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckPortugalAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckNetherlands", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckNetherlandsAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckItaly", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckItalyAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckIreland", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckIrelandAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/Check", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckIndia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckIndiaAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckHungary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckHungaryAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckUAE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckUAEAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckSlovakia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckSlovakiaAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckSriLanka", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckSriLankaAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckCzechRepublic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckCzechRepublicAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckCroatia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckCroatiaAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckBelgium", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckBelgiumAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckRussia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckRussiaAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckPakistan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckPakistanAsync(string RegistrationNumber, string state, string district, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/VinCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> VinCheckAsync(string Vin, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckMotorBikeUK", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckMotorBikeUKAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckNigeria", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckNigeriaAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckArgentina", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckArgentinaAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckChile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckChileAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckGermany", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckGermanyAsync(string KBANumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckAustria", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckAustriaAsync(int NatCode, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckSingapore", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckSingaporeAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckBrazil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckBrazilAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckMexico", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckMexicoAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckPeru", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckPeruAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckBolivia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckBoliviaAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckEcuador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckEcuadorAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckColombia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckColombiaAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckCyprus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckCyprusAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckUkraine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckUkraineAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckIceland", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckIcelandAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckLatvia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckLatviaAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckIsrael", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckIsraelAsync(string RegistrationNumber, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regcheck.org.uk/CheckMalaysia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckMalaysiaAsync(string RegistrationNumber, string username);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://regcheck.org.uk")]
    public partial class DataGrid
    {
        
        private string jsonField;
        
        private string[] columnNamesField;
        
        private string[][] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string json
        {
            get
            {
                return this.jsonField;
            }
            set
            {
                this.jsonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] columnNames
        {
            get
            {
                return this.columnNamesField;
            }
            set
            {
                this.columnNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://regcheck.org.uk")]
    public partial class Vehicle
    {
        
        private string vehicleJsonField;
        
        private VehicleVehicleData vehicleDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string vehicleJson
        {
            get
            {
                return this.vehicleJsonField;
            }
            set
            {
                this.vehicleJsonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VehicleVehicleData vehicleData
        {
            get
            {
                return this.vehicleDataField;
            }
            set
            {
                this.vehicleDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleData
    {
        
        private VehicleVehicleDataABICode aBICodeField;
        
        private VehicleVehicleDataDescription descriptionField;
        
        private VehicleVehicleDataRegistrationYear registrationYearField;
        
        private VehicleVehicleDataManufactureYearFrom manufactureYearFromField;
        
        private VehicleVehicleDataManufactureYearTo manufactureYearToField;
        
        private VehicleVehicleDataCarMake carMakeField;
        
        private VehicleVehicleDataCarModel carModelField;
        
        private VehicleVehicleDataBodyStyle bodyStyleField;
        
        private VehicleVehicleDataEngineSize engineSizeField;
        
        private VehicleVehicleDataNumberOfDoors numberOfDoorsField;
        
        private VehicleVehicleDataTransmission transmissionField;
        
        private VehicleVehicleDataFuelType fuelTypeField;
        
        private VehicleVehicleDataMakeDescription makeDescriptionField;
        
        private VehicleVehicleDataModelDescription modelDescriptionField;
        
        private VehicleVehicleDataImmobiliser immobiliserField;
        
        private VehicleVehicleDataNumberOfSeats numberOfSeatsField;
        
        private VehicleVehicleDataIndicativeValue indicativeValueField;
        
        private VehicleVehicleDataDriverSide driverSideField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleVehicleDataABICode ABICode
        {
            get
            {
                return this.aBICodeField;
            }
            set
            {
                this.aBICodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VehicleVehicleDataDescription Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public VehicleVehicleDataRegistrationYear RegistrationYear
        {
            get
            {
                return this.registrationYearField;
            }
            set
            {
                this.registrationYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public VehicleVehicleDataManufactureYearFrom ManufactureYearFrom
        {
            get
            {
                return this.manufactureYearFromField;
            }
            set
            {
                this.manufactureYearFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public VehicleVehicleDataManufactureYearTo ManufactureYearTo
        {
            get
            {
                return this.manufactureYearToField;
            }
            set
            {
                this.manufactureYearToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public VehicleVehicleDataCarMake CarMake
        {
            get
            {
                return this.carMakeField;
            }
            set
            {
                this.carMakeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public VehicleVehicleDataCarModel CarModel
        {
            get
            {
                return this.carModelField;
            }
            set
            {
                this.carModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public VehicleVehicleDataBodyStyle BodyStyle
        {
            get
            {
                return this.bodyStyleField;
            }
            set
            {
                this.bodyStyleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public VehicleVehicleDataEngineSize EngineSize
        {
            get
            {
                return this.engineSizeField;
            }
            set
            {
                this.engineSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public VehicleVehicleDataNumberOfDoors NumberOfDoors
        {
            get
            {
                return this.numberOfDoorsField;
            }
            set
            {
                this.numberOfDoorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public VehicleVehicleDataTransmission Transmission
        {
            get
            {
                return this.transmissionField;
            }
            set
            {
                this.transmissionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public VehicleVehicleDataFuelType FuelType
        {
            get
            {
                return this.fuelTypeField;
            }
            set
            {
                this.fuelTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public VehicleVehicleDataMakeDescription MakeDescription
        {
            get
            {
                return this.makeDescriptionField;
            }
            set
            {
                this.makeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public VehicleVehicleDataModelDescription ModelDescription
        {
            get
            {
                return this.modelDescriptionField;
            }
            set
            {
                this.modelDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public VehicleVehicleDataImmobiliser Immobiliser
        {
            get
            {
                return this.immobiliserField;
            }
            set
            {
                this.immobiliserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public VehicleVehicleDataNumberOfSeats NumberOfSeats
        {
            get
            {
                return this.numberOfSeatsField;
            }
            set
            {
                this.numberOfSeatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public VehicleVehicleDataIndicativeValue IndicativeValue
        {
            get
            {
                return this.indicativeValueField;
            }
            set
            {
                this.indicativeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public VehicleVehicleDataDriverSide DriverSide
        {
            get
            {
                return this.driverSideField;
            }
            set
            {
                this.driverSideField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataABICode
    {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataDescription
    {
        
        private string typeField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataRegistrationYear
    {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataManufactureYearFrom
    {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataManufactureYearTo
    {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataCarMake
    {
        
        private VehicleVehicleDataCarMakeCurrentValue currentValueField;
        
        private VehicleVehicleDataCarMakeCurrentTextValue currentTextValueField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleVehicleDataCarMakeCurrentValue CurrentValue
        {
            get
            {
                return this.currentValueField;
            }
            set
            {
                this.currentValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VehicleVehicleDataCarMakeCurrentTextValue CurrentTextValue
        {
            get
            {
                return this.currentTextValueField;
            }
            set
            {
                this.currentTextValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataCarMakeCurrentValue
    {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataCarMakeCurrentTextValue
    {
        
        private string typeField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataCarModel
    {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataBodyStyle
    {
        
        private VehicleVehicleDataBodyStyleCurrentValue currentValueField;
        
        private VehicleVehicleDataBodyStyleCurrentTextValue currentTextValueField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleVehicleDataBodyStyleCurrentValue CurrentValue
        {
            get
            {
                return this.currentValueField;
            }
            set
            {
                this.currentValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VehicleVehicleDataBodyStyleCurrentTextValue CurrentTextValue
        {
            get
            {
                return this.currentTextValueField;
            }
            set
            {
                this.currentTextValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataBodyStyleCurrentValue
    {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataBodyStyleCurrentTextValue
    {
        
        private string typeField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataEngineSize
    {
        
        private VehicleVehicleDataEngineSizeCurrentValue currentValueField;
        
        private VehicleVehicleDataEngineSizeCurrentTextValue currentTextValueField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleVehicleDataEngineSizeCurrentValue CurrentValue
        {
            get
            {
                return this.currentValueField;
            }
            set
            {
                this.currentValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VehicleVehicleDataEngineSizeCurrentTextValue CurrentTextValue
        {
            get
            {
                return this.currentTextValueField;
            }
            set
            {
                this.currentTextValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataEngineSizeCurrentValue
    {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataEngineSizeCurrentTextValue
    {
        
        private string typeField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataNumberOfDoors
    {
        
        private VehicleVehicleDataNumberOfDoorsCurrentValue currentValueField;
        
        private VehicleVehicleDataNumberOfDoorsCurrentTextValue currentTextValueField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleVehicleDataNumberOfDoorsCurrentValue CurrentValue
        {
            get
            {
                return this.currentValueField;
            }
            set
            {
                this.currentValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VehicleVehicleDataNumberOfDoorsCurrentTextValue CurrentTextValue
        {
            get
            {
                return this.currentTextValueField;
            }
            set
            {
                this.currentTextValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataNumberOfDoorsCurrentValue
    {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataNumberOfDoorsCurrentTextValue
    {
        
        private string typeField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataTransmission
    {
        
        private VehicleVehicleDataTransmissionCurrentValue currentValueField;
        
        private VehicleVehicleDataTransmissionCurrentTextValue currentTextValueField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleVehicleDataTransmissionCurrentValue CurrentValue
        {
            get
            {
                return this.currentValueField;
            }
            set
            {
                this.currentValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VehicleVehicleDataTransmissionCurrentTextValue CurrentTextValue
        {
            get
            {
                return this.currentTextValueField;
            }
            set
            {
                this.currentTextValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataTransmissionCurrentValue
    {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataTransmissionCurrentTextValue
    {
        
        private string typeField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataFuelType
    {
        
        private VehicleVehicleDataFuelTypeCurrentValue currentValueField;
        
        private VehicleVehicleDataFuelTypeCurrentTextValue currentTextValueField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleVehicleDataFuelTypeCurrentValue CurrentValue
        {
            get
            {
                return this.currentValueField;
            }
            set
            {
                this.currentValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VehicleVehicleDataFuelTypeCurrentTextValue CurrentTextValue
        {
            get
            {
                return this.currentTextValueField;
            }
            set
            {
                this.currentTextValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataFuelTypeCurrentValue
    {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataFuelTypeCurrentTextValue
    {
        
        private string typeField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataMakeDescription
    {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="NCName")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataModelDescription
    {
        
        private string typeField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataImmobiliser
    {
        
        private VehicleVehicleDataImmobiliserCurrentValue currentValueField;
        
        private VehicleVehicleDataImmobiliserCurrentTextValue currentTextValueField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleVehicleDataImmobiliserCurrentValue CurrentValue
        {
            get
            {
                return this.currentValueField;
            }
            set
            {
                this.currentValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VehicleVehicleDataImmobiliserCurrentTextValue CurrentTextValue
        {
            get
            {
                return this.currentTextValueField;
            }
            set
            {
                this.currentTextValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataImmobiliserCurrentValue
    {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataImmobiliserCurrentTextValue
    {
        
        private string typeField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataNumberOfSeats
    {
        
        private VehicleVehicleDataNumberOfSeatsCurrentValue currentValueField;
        
        private VehicleVehicleDataNumberOfSeatsCurrentTextValue currentTextValueField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleVehicleDataNumberOfSeatsCurrentValue CurrentValue
        {
            get
            {
                return this.currentValueField;
            }
            set
            {
                this.currentValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VehicleVehicleDataNumberOfSeatsCurrentTextValue CurrentTextValue
        {
            get
            {
                return this.currentTextValueField;
            }
            set
            {
                this.currentTextValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataNumberOfSeatsCurrentValue
    {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataNumberOfSeatsCurrentTextValue
    {
        
        private string typeField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataIndicativeValue
    {
        
        private string typeField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataDriverSide
    {
        
        private VehicleVehicleDataDriverSideCurrentValue currentValueField;
        
        private VehicleVehicleDataDriverSideCurrentTextValue currentTextValueField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleVehicleDataDriverSideCurrentValue CurrentValue
        {
            get
            {
                return this.currentValueField;
            }
            set
            {
                this.currentValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VehicleVehicleDataDriverSideCurrentTextValue CurrentTextValue
        {
            get
            {
                return this.currentTextValueField;
            }
            set
            {
                this.currentTextValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataDriverSideCurrentValue
    {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://regcheck.org.uk")]
    public partial class VehicleVehicleDataDriverSideCurrentTextValue
    {
        
        private string typeField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://regcheck.org.uk")]
    public partial class UKTest
    {
        
        private string testDateField;
        
        private string expiryDateField;
        
        private string resultField;
        
        private string odometerField;
        
        private string testNumberField;
        
        private string[] failureReasonsField;
        
        private string[] advisoriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TestDate
        {
            get
            {
                return this.testDateField;
            }
            set
            {
                this.testDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ExpiryDate
        {
            get
            {
                return this.expiryDateField;
            }
            set
            {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Odometer
        {
            get
            {
                return this.odometerField;
            }
            set
            {
                this.odometerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TestNumber
        {
            get
            {
                return this.testNumberField;
            }
            set
            {
                this.testNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public string[] FailureReasons
        {
            get
            {
                return this.failureReasonsField;
            }
            set
            {
                this.failureReasonsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public string[] Advisories
        {
            get
            {
                return this.advisoriesField;
            }
            set
            {
                this.advisoriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://regcheck.org.uk")]
    public partial class UKMOTData
    {
        
        private UKTest[] testsField;
        
        private string taxDateField;
        
        private string jsonField;
        
        private string[][] extendedInformationField;
        
        private string extendedInformationJsonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public UKTest[] Tests
        {
            get
            {
                return this.testsField;
            }
            set
            {
                this.testsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string taxDate
        {
            get
            {
                return this.taxDateField;
            }
            set
            {
                this.taxDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Json
        {
            get
            {
                return this.jsonField;
            }
            set
            {
                this.jsonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] ExtendedInformation
        {
            get
            {
                return this.extendedInformationField;
            }
            set
            {
                this.extendedInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ExtendedInformationJson
        {
            get
            {
                return this.extendedInformationJsonField;
            }
            set
            {
                this.extendedInformationJsonField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface CarRegSoapChannel : RegCheckService.CarRegSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class CarRegSoapClient : System.ServiceModel.ClientBase<RegCheckService.CarRegSoap>, RegCheckService.CarRegSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CarRegSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CarRegSoapClient.GetBindingForEndpoint(endpointConfiguration), CarRegSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarRegSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CarRegSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarRegSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CarRegSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarRegSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<RegCheckService.DataGrid> CarSpecificationsAsync(string make, string model, int year)
        {
            return base.Channel.CarSpecificationsAsync(make, model, year);
        }
        
        public System.Threading.Tasks.Task<string> WheelSizeAsync(string make, string model, int year)
        {
            return base.Channel.WheelSizeAsync(make, model, year);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.UKMOTData> UKMOTAsync(string RegistrationNumber, string Model, string username)
        {
            return base.Channel.UKMOTAsync(RegistrationNumber, Model, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckSouthAfricaAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckSouthAfricaAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckEstoniaAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckEstoniaAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckNewZealandAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckNewZealandAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckUSAAsync(string RegistrationNumber, string State, string username)
        {
            return base.Channel.CheckUSAAsync(RegistrationNumber, State, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckAustraliaAsync(string RegistrationNumber, string State, string username)
        {
            return base.Channel.CheckAustraliaAsync(RegistrationNumber, State, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckSpainAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckSpainAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckFranceAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckFranceAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckDenmarkAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckDenmarkAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckFinlandAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckFinlandAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckSwedenAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckSwedenAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckNorwayAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckNorwayAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckPortugalAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckPortugalAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckNetherlandsAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckNetherlandsAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckItalyAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckItalyAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckIrelandAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckIrelandAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckIndiaAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckIndiaAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckHungaryAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckHungaryAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckUAEAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckUAEAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckSlovakiaAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckSlovakiaAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckSriLankaAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckSriLankaAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckCzechRepublicAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckCzechRepublicAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckCroatiaAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckCroatiaAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckBelgiumAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckBelgiumAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckRussiaAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckRussiaAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckPakistanAsync(string RegistrationNumber, string state, string district, string username)
        {
            return base.Channel.CheckPakistanAsync(RegistrationNumber, state, district, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> VinCheckAsync(string Vin, string username)
        {
            return base.Channel.VinCheckAsync(Vin, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckMotorBikeUKAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckMotorBikeUKAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckNigeriaAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckNigeriaAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckArgentinaAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckArgentinaAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckChileAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckChileAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckGermanyAsync(string KBANumber, string username)
        {
            return base.Channel.CheckGermanyAsync(KBANumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckAustriaAsync(int NatCode, string username)
        {
            return base.Channel.CheckAustriaAsync(NatCode, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckSingaporeAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckSingaporeAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckBrazilAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckBrazilAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckMexicoAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckMexicoAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckPeruAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckPeruAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckBoliviaAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckBoliviaAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckEcuadorAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckEcuadorAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckColombiaAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckColombiaAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckCyprusAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckCyprusAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckUkraineAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckUkraineAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckIcelandAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckIcelandAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckLatviaAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckLatviaAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckIsraelAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckIsraelAsync(RegistrationNumber, username);
        }
        
        public System.Threading.Tasks.Task<RegCheckService.Vehicle> CheckMalaysiaAsync(string RegistrationNumber, string username)
        {
            return base.Channel.CheckMalaysiaAsync(RegistrationNumber, username);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CarRegSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CarRegSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CarRegSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://www.regcheck.org.uk/api/reg.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CarRegSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://www.regcheck.org.uk/api/reg.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CarRegSoap,
            
            CarRegSoap12,
        }
    }
}
